### ISSUE TITLE
[BUG] Player doesn't work for restricted videos

### ISSUE THREAD

**Issue by ballo** [Andrews54757/FastStream#280] opened 2024-11-02 06:59 UTC
Title says it all. Restricted videos (like cop body cam videos showing violence) on YouTube require a click-through. These videos don't work with this player.

**Comment by Andrews54757** [comment] 2024-11-02 16:41
Duplicate of #262 . We are working on it but Youtube doesn't make it easy.

**Closed as not planned by Andrews54757** 2024-11-02 16:41 UTC
