### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by gt-nik** [Andrews54757/FastStream#4] opened 2023-11-04 12:32 UTC
Hi Andrew,

FS 1.1.18 on Firefox Portable 119.0

I would like to ask for some new features please:

**New FS Options:**
1. If browser has the download option "always ask where to save files" enabled, Bypass this Browser Dialog and download immediately to downloads folder.
2. Download speed limit (Global/Total for all files currently been downloaded by FS only).

**New FS Features:**

1. FS Save As dialog will provide two names (both editable fields) for the user to select one: a)movie file Name b)page title.
2. If Firefox internal download manager fails to save the file, inform user and keep the 100% buffered data until user close the Tab (probably user will try to save again, so do not download all data again).
3. While a save as/downloading procedure is running, a Tab-close event will Warn user and allow to cancel the close and continue the procedure.
4. Left mouse click on video frame will toggle Play/Pause.

**PS**
FS 1.1.18 is working very good on Firefox - Looking for the same fixes for Chrome.

Thanks
Best Regards

**Comment by Andrews54757** [comment] 2023-11-04 17:59
@gt-nik Thank you for your suggestions

**New options:**

1. To my knowledge, it is not possible to detect if the user has this option enabled. I would have to create a new FastStream option to download without dialog.
2. Download speed limit is a good idea and I will work on it.

**New features:**

1. It isn't possible to provide two different names
2. Buffered data is already kept until tab close if you are not in incognito mode. Buffer is always cleared in incognito mode because incognito mode/privacy mode doesn't allow the use of IndexedDB. Your computer will run out of memory if I don't clear it.
3. I don't like dialogs that prevent user from closing the tab. What if a user wants to quickly close the tab using `Cmd+W`?
4. Double click to toggle play/pause. Single click will hide controls. This is the same behavior as MacOS' QuickTime player.

**Comment by gt-nik** [comment] 2023-11-05 07:13
Hi Andrew,
Thank you for your quick reply.

- **About New Features 1:** In my opinion, most of the times, the tab/page title contains the title of the movie. There are many video servers that name all movies as "video.mp4" but the title of the page with the player has the full name "Movie Once Upon a Studio (2023) online with Greek subtitles Comedy".
- **About New Features 2:** Now: click on save button > Ask for name > Saving 0% ... 100% > Firefox download manager=compete. There is no re-download option in Firefox download manager to save again from buffer. If i click on save button again, it will again Ask for name > Saving 0% ... 100% > Firefox download manager=compete. So in this case first buffer is ignored. How to save again already buffered video (in case browser download fail or file accidentally deleted)? (option "Predownload entire video in the background if possible" is disabled) [console-export-2023-11-5_8-14-44.txt](https://github.com/Andrews54757/FastStream/files/13258806/console-export-2023-11-5_8-14-44.txt)

**New features:**
**5.** Match the Subtitle name with the already provided video name (a1,a2) **and vice versa** Match the video name with the already provided Subtitle name (b1,b2):
a1) Save video > ask for name (default="33") > I set name="My Movie 1"> ok > Saved As "My Movie 1.mp4"
a2) Save Subtitle > ask for name (default="(el)_ye6svaxbhod2_Greek") - here i am expecting to provide the same name i set for the movie ("My Movie 1" vtt, srt, ...)
In the same way:
b1) Save Subtitle > ask for name (default="(el)_ye6svaxbhod2_Greek") > I set name="My Movie 1"> ok > Saved As "My Movie 1.srt"
b2) Save video > ask for name (default="33") > here i am expecting to provide the same name i set for the Subtitle "My Movie 1"

Thanks

**Comment by Andrews54757** [comment] 2023-11-05 07:57
1. The player already sets the placeholder name based on information extracted from the page title. See below:

https://github.com/Andrews54757/FastStream/blob/b1a7776bb7b5e7c0009edf3bdcd59385b5e22715/chrome/background/background.mjs#L312-L344

2. Are you sure that the buffer is being ignored? When it says it is saving, it is converting the file to MP4. This can take a while, but it doesn't mean it is redownloading everything again. Storing the result of the converted file in a buffer is not ideal as it would use twice the amount of storage.

5. Subtitle track name placeholder is the name of track given by the website. If I change the behavior here, it would affect users who rely on the original name to distinguish different tracks.

**Comment by gt-nik** [comment] 2023-11-05 09:27
2. It seems that buffer is ignored when i press save button for a second time. It asks again for name, saving again 0%...100% and according to log 1st time="save took 17.222s" and 2nd time= "save took 18.825s" 
[console-export-2023-11-5_10-18-41.txt](https://github.com/Andrews54757/FastStream/files/13258994/console-export-2023-11-5_10-18-41.txt)

**Comment by Andrews54757** [comment] 2023-11-05 17:48
Make sure that the "predownload entire video in background" option is set. Your computer will also need to have enough storage.

**Comment by gt-nik** [comment] 2023-11-06 07:25
As i already wrote in [my message](https://github.com/Andrews54757/FastStream/issues/4#issuecomment-1793658486) (before the console-export file) : option "Predownload entire video in the background if possible" is disabled.

If i enable it, it works.

Maybe it has to be enabled internally, temporary and for this tab only, when the user start the save as procedure. I don't like to enable this option globally if i only need to watch/play the movie without download it.

**Comment by Andrews54757** [comment] 2023-11-06 14:40
It is working as intended. If the user chooses to buffer only a small portion of the video by unsetting that option, the player will not store more data than what is strictly necessary. Saving twice using the same built file is not a supported feature anymore because it used too much memory (your other issue #1 led to its removal). Technically speaking, the download process now is able to stream data directly to the downloads folder for Chrome. Caching the file again would invalidate this.

**Comment by Andrews54757** [comment] 2023-11-07 06:25
Version 1.1.19 has been released with the "Target download speed of player during video playback" option. This will limit the download speed on a per-player basis.

Note that user-action initiated content downloads, such as hovering for video preview, will proceed while ignoring this option. Only background pre-download process is affected.

**Closed as completed by Andrews54757** 2023-11-07 06:25 UTC
