### ISSUE TITLE
[BUG] Many fragments failing on Youtube

### ISSUE THREAD

**Issue by vicksystem** [Andrews54757/FastStream#191] opened 2024-07-20 18:29 UTC
All the videos I'm going to watch feature this:
![Captura de tela_20-7-2024_152733_www youtube com](https://github.com/user-attachments/assets/69dc3d2c-f7b2-4bfc-aa17-f38400968476)

**Comment by Andrews54757** [comment] 2024-07-20 18:45
Try following the steps in #164 (copied below)

**Comment by Andrews54757** [comment] 2024-07-20 18:45
Note: Some users are reporting that they are getting failed fragments, 403 errors on youtube after the update. This is likely because of the cache still using old tokens. Please do the following:

1. Open developer tools on Youtube
2. Click "Application"
3. Under "Storage", find "youtubei.js". Click it.
4. Click delete database.
5. Reload the video

![image](https://github.com/Andrews54757/FastStream/assets/13282284/ef05bb8d-b3a2-446a-8cee-0aa85fb5b49d)

**Comment by Andrews54757** [comment] 2024-07-20 18:48
Also, make sure that your faststream version is up to date. Youtube will often change things to break 3rd party players.

**Comment by vicksystem** [comment] 2024-07-20 18:59
> Nota: Alguns usuários estão relatando que estão recebendo fragmentos com falha, erros 403 no youtube após a atualização. Isso provavelmente se deve ao cache ainda usar tokens antigos. Faça o seguinte:
> 
> 1. Abrir ferramentas para desenvolvedores no Youtube
> 2. Clique em "Aplicativo"
> 3. Em "Armazenamento", localize "youtubei.js". Clique nele.
> 4. Clique em excluir banco de dados.
> 5. Recarregar o vídeo
> 
> ![image](https://private-user-images.githubusercontent.com/13282284/347647890-ef05bb8d-b3a2-446a-8cee-0aa85fb5b49d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MDE5NzgsIm5iZiI6MTcyMTUwMTY3OCwicGF0aCI6Ii8xMzI4MjI4NC8zNDc2NDc4OTAtZWYwNWJiOGQtYjNhMi00NDZhLThjZWUtMGFhODVmYjViNDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDE4NTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZTQ4MzA3Y2M1MjkxMzcwMjJjNjI2ODAxMjkzOGNmNjhkOTRhNGVjZjkzYjdiODkzNWQ3NjhkNTVmYmMyOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R3-wP7THCkurwUvSO7abpD9JgO55C_Uxs9Q8UhMEAkw)

**Comment by vicksystem** [comment] 2024-07-20 19:06
does not appear youtubei.js

**Comment by Andrews54757** [comment] 2024-07-20 19:09
Scroll down, it could be at the bottom of the list. Please send me a picture of what you have listed.

**Comment by vicksystem** [comment] 2024-07-20 19:17
![photo_2024-07-20_16-13-37](https://github.com/user-attachments/assets/f6fab7df-4b8e-4843-9988-e0a473f4ceaa)

**Comment by Andrews54757** [comment] 2024-07-20 19:24
Very strange. What faststream version are you on?

**Comment by vicksystem** [comment] 2024-07-20 19:28
v 1.3.14

**Comment by freezewind** [comment] 2024-07-21 13:55
I also reproduced this issue in Firefox esr v115 with 1.3.14.
It only happens in private window.
Update: I can't reproduce this issue anymore today. May be Youtube is doing some A/B testing, so only some people can reprodece this issue.

**Comment by Andrews54757** [comment] 2024-07-25 01:16
May be related to #192 . Closing as fix deployed in V1.3.15

**Closed as completed by Andrews54757** 2024-07-25 01:16 UTC
Labels: Youtube Issue
