### ISSUE TITLE
Youtube skips video when using FastStream on a playlist

### ISSUE THREAD

**Issue by bachig26** [Andrews54757/FastStream#22] opened 2023-11-23 05:49 UTC
**Describe the bug**
As you can see in the clip, the video gets skipped to next video once the FastStream starts to load the content video in the playlist.
I haven't checked the other sites like dailymotion or etc, for this issue, 

#### Clip

https://github.com/Andrews54757/FastStream/assets/96393348/a628f5a5-a98b-4149-a2c4-39797a05579b

**Version**
FastStream v1.2.2

**Platform**
Vivaldi: 6.4.3160.44 (Stable channel) (64-bit), Chromium/118.0.5993.146

**Comment by Andrews54757** [comment] 2023-11-23 05:59
Thanks for letting me know! Looks like Youtube will go to the next video when it detects video fails to play. I will investigate further.

**Comment by Andrews54757** [comment] 2023-11-23 06:08
Hmm, I'm having trouble reproducing this issue on Chrome. I can't get the video skipping to occur with FastStream V1.2.4. Perhaps the issue is only on 1.2.2? Please update the extension and let me know if it works. (Note, the update is still under review by Google for the chrome web store edition, I recommend you try installing from source).

<img width="1512" alt="it works" src="https://github.com/Andrews54757/FastStream/assets/13282284/78ee4212-50aa-4687-b942-f23151f64962">

**Comment by Andrews54757** [comment] 2023-11-26 02:06
Closing as resolved, might be fixed in 1.2.4.

**Closed as completed by Andrews54757** 2023-11-26 02:06 UTC
Labels: bug, need more information, unable to reproduce
